export const FETCH_MUSICS_FIND = 'FETCH_MUSICS_FIND';
export const FETCH_MUSICS_FIND_SUCCESS = 'FETCH_MUSICS_FIND_SUCCESS';
export const FETCH_MUSICS_FIND_FAILED = 'FETCH_MUSICS_FIND_FAILED';
export const FETCH_VITRINES = 'FETCH_VITRINES';
export const FETCH_VITRINES_SUCCESS = 'FETCH_VITRINES_SUCCESS';
export const FETCH_VITRINES_FAILED = 'FETCH_VITRINES_FAILED';
